public enum StateEnum
{
    Dead,
    Patrolling,
    Lookout,
    Hiding,
    Hidden,
    Dragging,
    DraggingStart,
    InCombat,
    Crouching,
    Attacking,
    IsChargingLeftAttack,
    IsChargingRightAttack,
    Pickup,
    Inspecting,
    Running,
    SawSomethingSuspicious,
}